---
- name: environment setup
  hosts: localhost
  vars_files: vars.yaml
  tasks:
  - name: add terraform repo
    shell: dnf config-manager --add-repo=https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
  - name: install system packages
    yum:
      name: "{{ item }}"
      state: latest
    loop:
      - python3
      - python3-pip
      - unzip
      - yum-utils
      - podman-docker
      - terraform
  - name: upgrade ansible-core
    shell: "{{ item }}"
    loop:
      - 'python3 -m pip install --upgrade ansible-core'
  - name: install python dependencies
    pip:
      name: "{{ item }}"
      state: present
    loop:
      - boto3==1.28.0
      - botocore==1.31.0
      - requests==2.28.2
      - flask==3.1.0
  - name: check if aws cli is installed
    command: "which aws"
    register: aws_cli_check
    ignore_errors: true
  - name: download and unzip aws-cli
    unarchive:
      src: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
      dest: ../
      remote_src: yes
    when: aws_cli_check.rc != 0
  - name: install aws-cli and configure credentials
    shell: "{{ item }}"
    loop:
      - 'sudo ../aws/install'
      - 'aws configure set aws_access_key_id {{ aws_access_key_id }}'
      - 'aws configure set aws_secret_access_key {{ aws_secret_access_key }}'
      - 'aws configure set default.region {{ defaultregion }}'
    when: aws_cli_check.rc != 0
  tags: env


- name: push image to ecs repository
  hosts: localhost
  vars_files: vars.yaml
  gather_facts: false
  tasks:
  - name: create aws ecr repository
    community.aws.ecs_ecr:
      name: "{{ project_name }}"
  - name: setup ecr with docker, build, and tag image
    shell: "{{ item }}"
    loop:
      - "aws ecr get-login-password --region us-east-1 | podman login --username AWS --password-stdin {{ aws_account_id }}.dkr.ecr.us-east-1.amazonaws.com"
      - "sleep 5"
      - "podman build --platform linux/amd64 -t {{ project_name }} ."
      - "podman tag {{ project_name }}:latest {{ aws_account_id }}.dkr.ecr.us-east-1.amazonaws.com/{{ project_name }}:latest"
  - name: push image to ecr
    shell: "podman push {{ aws_account_id }}.dkr.ecr.us-east-1.amazonaws.com/{{ project_name }}:latest"
  - name: update ecr repo variable for terraform
    lineinfile:
      path: "./terraform/myvars.tfvars"
      line: 'ecr_repository_name = "{{ project_name }}"'
